FROM python:3.10
LABEL authors="RMNorbert"
# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app
# Copy the intents into the container at /app
COPY chatbot/data/intents.json /app/data/intents.json


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Train of the modell. Use this if there are any changes in the intents.json file
# RUN python chatbot/train.py

# Make the port available to the world outside the container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]
