FROM python:3.8
LABEL authors="RMNorbert"
# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

COPY chatbot/intents.json /app/intents.json
#COPY app.py /app/app.py

# Install any needed packages specified in requirements.txt
RUN pip install torch nltk numpy flask

# Copy the intents into the container at /app

RUN python chatbot/train.py
# Make the port available to the world outside the container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]